# Suggested minimal codemagic.yaml template
workflows:
  build_android:
    name: Build Android
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build apk
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Install deps
        script: |
          flutter pub get
      - name: Build ipa
        script: |
          flutter build ipa --export-method ad-hoc
    # Publishing to App Store Connect should use the publishing section with the
    # exact allowed keys. If you previously had keys like `ipa_path` or
    # `itc_team_id` under publishing/app_store_connect and got errors,
    # move them to an `app_store_connect` publisher block as per the latest docs.
