workflows:
  android-build:
    name: Build Android
    instance_type: mac_mini_m1  # Or 'linux_x2' for faster builds
    environment:
      groups:
        - flutter_stable
    scripts:
      - flutter doctor -v
      - flutter pub get
      - flutter test
      - flutter build apk --release  # For APK
      - flutter build appbundle --release  # For App Bundle
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # APK file
      - build/app/outputs/bundle/release/app-release.aab  # App Bundle
    publishing:
      email:
        recipients:
          - your.email@example.com  mkhanbirhmani@gmail.com
