name: birhmani_ai_ludo
description: Birhmani AI Ludo - Utraadi Ludo (Black neon themed Ludo with Gemini AI integration)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flame: ^1.18.0
  audioplayers: ^6.1.0
  google_generative_ai: ^0.4.0
  shared_preferences: ^2.3.2
  lottie: ^3.1.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/board.png
    - assets/images/token_red.png
    - assets/images/token_blue.png
    - assets/images/token_green.png
    - assets/images/token_yellow.png
    - assets/images/dice_1.png
    - assets/images/dice_2.png
    - assets/images/dice_3.png
    - assets/images/dice_4.png
    - assets/images/dice_5.png
    - assets/images/dice_6.png
    - assets/images/neon_button.png
    - assets/images/token_alt_red.png
    - assets/images/token_alt_blue.png
    - assets/images/token_alt_green.png
    - assets/images/token_alt_yellow.png
    - assets/images/dice_skin_1.png
    - assets/images/dice_skin_2.png
    - assets/animations/welcome.json
    - assets/animations/confetti.json
    - assets/sounds/dice_roll.mp3
    - assets/sounds/win.mp3
    - assets/sounds/bg_music.mp3
